local list_suite = Suite("redis list suite")
list_suite.setup(function()
  _.outlet.list({"command","flushdb"})
end)
list_suite.teardown(function()
  _.outlet.list({"command","flushdb"})
end)

list_suite.case("LRANGE"
  ).test(function()
    _.outlet.list({"command","RPUSH","MYLIST","MYVALUE1"})
    _.outlet.list({"command","RPUSH","MYLIST","MYVALUE2"})
    _.outlet.list({"command","RPUSH","MYLIST","MYVALUE3"})
    Test.list({"command","LRANGE","MYLIST","0","-1"})
  end).should:equal({"MYVALUE1","MYVALUE2","MYVALUE3"})